# Generated by Django 4.2.7 on 2023-11-18 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "10S"),
                            (2, "1M"),
                            (3, "5M"),
                            (4, "10M"),
                            (5, "15M"),
                            (6, "1H"),
                            (7, "4H"),
                        ]
                    ),
                ),
                (
                    "sma_duration",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
            ],
        ),
    ]
